# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:  
  push: 
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: log repo name to console
        run: echo 'Repsoitory name  $GITHUB_REPOSITORY'
      
      - uses: action/checkout@v2
      - name: build container image and push to registry
        uses: docker/build-push-action@v1
        with: 
          username: ${{ secrets.My_Secret }}
          password: ${{ secrets.My_Secret }}
          login-server: actionworkshops.azurecr.io
          repository: actionsworkshop.azurecr.io/githubactionsworkshop
          tags: latest, ${{github.sha}}
          
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: azure/login@1.1
        with: 
          creds: ${{ secrets.Azure_Credentials}}
          
      - uses: 'azure/aci-deploy@v1'
        id: aci-deploy
        with:
          resource-group: devopsdayams
          dns-name-label: wallofzen3
          image: ntrogh/wallofzen1:${{ github.sha}}
          name: ntwallofzen3
          location: 'west europe'
          environment-varibles: BASE_URL=HTTPS//devopsdaysams.azurewebsites.net/api/AddToWall
